version: '3.4'

x-app-base:
  &app-base
  build: &app-build-base
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh

services:
  app:
    <<: *app-base
    build:
      <<: *app-build-base
      target: development

  app-production:
    <<: *app-base
    build:
      <<: *app-build-base
      target: production

