version: '3.4'

# using extension fields is overkill in this scenario,
# but it can be useful if you need multiple similar
# instances of the same service
x-app-base:
  &app-base
  build: &app-build-base
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh

services:
  app:
    <<: *app-base
    build:
      <<: *app-build-base
      target: development

  app-production:
    <<: *app-base
    build:
      <<: *app-build-base
      target: production

