version: '3.4'

x-app-base:
  &app-base
  build: &app-build-base
    context: ${APP_BASE:-.}
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh
  env_file:
    - ${APP_BASE:-.}/app.env

services:
  app:
    <<: *app-base
    build:
      <<: *app-build-base
      target: development

  app-production:
    <<: *app-base
    build:
      <<: *app-build-base
      target: production
    profiles:
      - production

  shell-linter:
    image: koalaman/shellcheck-alpine:v0.7.1
    working_dir: /mnt/
    command:
      - scripts/lint_app.sh
    profiles:
      - shell-checker

