version: '3.4'

x-app-override:
  &app-override
  volumes:
    - ${APP_BASE:-.}:${APP_DIR}/

services:
  app:
    <<: *app-override

  app-production:
    <<: *app-override

  shell-linter:
    image: koalaman/shellcheck-alpine:v0.7.1
    working_dir: /mnt/
    command:
      - scripts/lint_app.sh
    volumes:
      - ${APP_BASE:-.}:/mnt/
    deploy:
      replicas: 0

