name: publish_continer_image
run-name: Publishing bash container image
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: echo "working"
