name: publish_continer_image
run-name: Publishing bash container imagee
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "working"
