name: publish_continer_image
run-name: Publishing bash container image
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Extract Meta Information for Docker Image
        uses: docker/metadata-action@v5
        id: meta
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.meta.outputs.tags }}"
      - run: echo "${{ steps.meta.outputs.labels }}"
      - name: Build and Push Image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}:latest
